### PR TITLE
Desktop version

### PR DESCRIPTION
**Pull request by abubakar83**
update style.css

### CODE REVIEW

**Review by jerryowusu — COMMENTED** [review]
Hi @abubakar83 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have any future feature listed in the readme file. Kindly also ensure that all other sections of the readme file are edited accordingly. :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by abubakar83** [comment]
@jerryowusu Thanks for giving me your comment on my project an "invalid code review request "
To be honest I do not understand what you want changes from my repo. 
Do I change or update my README.md file?

**Comment by abubakar83** [comment]
@jerryowusu I resolved the problem that you mentioned.

**Review by ha-manel — COMMENTED** [review]
# STATUS: INVALID 🔴 
Hi @abubakar83 
I'm sure you put a lot of effort into this project but this PR is invalid because your README file is almost empty 😓 

To clarify what the previous reviewer said: it's not enough to just copy the template, please fill it out with information related to your project like future features that you're gonna have, how to setup the project locally (clone, open with browser...) ...etc. Right now your README file is mostly just placeholder text which doesn't count as professional documentation 👍  
Kindly fix the issue and submit the PR for review again 💯 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by abubakar83** [comment]
@ha-manel finally I have done all my issues.

**Comment by huseyinbiyik** [comment]
Hi @abubakar83,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

❌Kindly fix the Pull Request description section, it should have a short summary describing the introduced changes for this branch. ❌
Capture-2022-12-16-210428



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
